name: Branch sync

on:
  workflow_call:
    inputs:
      from_branch:
        description: ""
        required: false
        type: string
      to_branch:
        description: ""
        required: false
        type: string

jobs:
  branch-sync:
    name: Branch sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up git
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "@github.com"

      - name: Push change from ${{ inputs.from_branch }} to ${{ inputs.to_branch }}
        run: |
          echo "Pushing ${{ inputs.from_branch }} to ${{ inputs.to_branch }}"
          # git fetch origin
          # git checkout ${{ inputs.to_branch }}
          # git merge ${{ inputs.from_branch }}
