name: Release

on:
  workflow_call:
    inputs:
      repository_owner:
        required: true
        type: string
      semantic_version:
        required: false
        type: string
        default: 23.0.2
      semantic_extra_plugins:
        required: false
        type: string
        default: |
          @semantic-release/changelog@6.0.3
          @semantic-release/git@10.0.1
          conventional-changelog-conventionalcommits@7.0.2
    secrets:
      semantic_release_token:
        description: "A token passed from the caller workflow"
        required: true
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    # Skip running release workflow on forks
    if: github.repository_owner == ${{ inputs.repository_owner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: ${{ inputs.semantic_version }}
          extra_plugins: ${{ inputs.semantic_extra_plugins }}
        env:
          GITHUB_TOKEN: ${{ secrets.semantic_release_token }}
