name: Sync Branches

on:
  workflow_call:
    inputs:
      from_branch:
        description: ""
        required: true
        type: string
      to_branch:
        description: ""
        required: true
        type: string
      merge_method:
        description: ""
        required: false
        type: string
        default: merge
    secrets:
      token:
        description: ""
        required: true

jobs:
  branch-sync:
    name: Sync Branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 12

      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.token }}
          FROM_BRANCH: ${{ inputs.from_branch }}
          TO_BRANCH: ${{ inputs.to_branch }}
          PULL_REQUEST_AUTO_MERGE_METHOD: ${{ inputs.merge_method }}
