name: Sync Branches

on:
  workflow_call:
    inputs:
      branch:
        description: ""
        required: true
        type: string
      force:
        description: ""
        required: false
        type: string
        default: false
    secrets:
      token:
        description: ""
        required: true

jobs:
  branch-sync:
    name: Sync Branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: connor-baer/action-sync-branch@main
        with:
          token: ${{ secrets.token }}
          branch: ${{ inputs.branch }}
          force: ${{ inputs.force }}
